---
title: "group_project"
author: "Abhay Sharma"
date: "2024-03-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
#Data initialization

library(tidyverse)

# Read data
data = read.csv("ObesityDataSet_raw_and_data_sinthetic.csv")
head(data)
names(data)

# Rename some variables for clarity
data <- data %>% rename(Obesity_Level = NObeyesdad) %>% 
  rename(Transportation_Use = MTRANS) %>%
  rename(Alcohol_Consump = CALC) %>%
  rename(Tech_Time = TUE) %>%
  rename(Physical_Activ_Amt = FAF) %>%
  rename(Monitor_Calories = SCC) %>%
  rename(Water_Consump = CH2O) %>%
  rename(Does_Smoke = SMOKE) %>%
  rename(Food_bw_Meals = CAEC) %>%
  rename(Main_Meal_Consump = NCP) %>%
  rename(Veggie_Consump = FCVC) %>%
  rename(HiCal_Food_Consump = FAVC) %>%
  rename(Family_History_w_Overweight = family_history_with_overweight) 

s# Check updated names
names(data)

# Add BMI variable
data <- data %>% 
  mutate(BMI = Weight/(Height^2)) 
```

