---
title: "Group project - Final"
output: pdf_document
date: "2024-03-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Initialization of data
data = read.csv("obesity.csv")

data <- data %>% 
  rename(
    Obesity_Level = NObeyesdad, Transportation_Use = MTRANS, Alcohol_Consump = CALC,
    Tech_Time = TUE, Physical_Activ_Amt = FAF, Monitor_Calories = SCC, Water_Consump = CH2O,
    Does_Smoke = SMOKE, Food_bw_Meals = CAEC, Main_Meal_Consump = NCP, Veggie_Consump = FCVC,
    HiCal_Food_Consump = FAVC, Family_History_w_Overweight = family_history_with_overweight
  )

# Add BMI variable
data <- data %>% 
  mutate(BMI = Weight/(Height^2)) 
```

```{r}
# BMI vs Gender
data %>% ggplot(aes(x=BMI, fill=Gender)) + geom_density()

```

``` {r}
# BMI vs Age - Younger people tend to have the most variation in BMI
data %>% ggplot(aes(x=Age, y=BMI)) + geom_point()

# Obesity_Level vs Age
data %>% ggplot(aes(x=Obesity_Level,y=Age)) + geom_boxplot()

data %>% ggplot(aes(fill=Obesity_Level,x=Age)) + geom_density()
```

```{r}
# BMI vs Family history
data %>%
  ggplot(aes(x = Family_History_w_Overweight, y = BMI, fill = Family_History_w_Overweight)) +
  geom_boxplot()

data %>% ggplot(aes(x=BMI,fill=Family_History_w_Overweight)) + geom_density()

data %>% ggplot(aes(x=BMI, fill=Family_History_w_Overweight)) + geom_histogram()
```

```{r}
# BMI vs HiCal_Food_Consump
data %>%
  ggplot(aes(x = HiCal_Food_Consump, y = BMI, fill = HiCal_Food_Consump)) +
  geom_boxplot()

ggplot(data, aes(x = BMI)) + geom_histogram(bins=20) + facet_grid(~HiCal_Food_Consump)
```

# Introduction

# Methods

# Results

# Conclusions

# References